type UnverifiedUser  {
	name: String!
	surname: String!
	email: String!
}

type Query {
	login(
	username: String!
	, password: String!): UnverifiedUser!
	helloWorld: String!
}

type Mutation {
	register(email: String!, password: String!): UnverifiedUser!
}