type UnverifiedUser  {
	username: String!
	email: String!
	firstname: String!
	lastname: String!
	token: String!
}

type Query {
	helloWorld: String!
}

type Mutation {
	register(username:String!, name: String!, surname: String!, email: String!, password: String!): UnverifiedUser!
	login(
	username: String!
	, password: String!): UnverifiedUser!
}