type UnverifiedUser  {
	name: String!
	surname: String!
	email: String!
}

type Query {
	helloWorld: String!
}

type Mutation {
	register(username:String!, name: String!, surname: String!, email: String!, password: String!): UnverifiedUser!
	login(
	username: String!
	, password: String!): UnverifiedUser!
}